### ISSUE TITLE
Latest pushed image is faulty

### ISSUE THREAD

**Issue by Vasfed** [Angatar/s3cmd#2]
Image that was pushed about an hour ago fails to run:
```
docker run --rm -it d3fk/s3cmd
Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 4, in <module>
    __import__('pkg_resources').run_script('s3cmd==2.4.0.dev0', 's3cmd')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```
Looks like `py3-setuptools` is used in runtime

**Comment by Angatar** [comment]
Thanks for reporting this! The last push should have fixed this issue.

**Comment by Angatar** [comment]
The latest version has well resolved the reported issue, however, a deprecation warning regarding the use of pkg_resources has emerged:
 
```sh
/usr/bin/s3cmd:4: DeprecationWarning: pkg_resources is deprecated as an API.
```
This warning appears to be linked to the use of the setup.py install method that is now deprecated. As it's no longer considered good practice to use pip on Alpine when a package is available, and to proactively mitigate potential future disruptions caused by these deprecated functionalities, the forthcoming version of the d3fk/s3cmd container image will make use of the apk manager leveraging an up-to-date Alpine s3cmd package available in the edge channel.

**Comment by Angatar** [comment]
Updated version pushed and working.
